title: Medical Report Analyzer
emoji: 🏥
colorFrom: blue
colorTo: green
sdk: docker
app_port: 8000
app:
  -!<!docker []: {filename: Dockerfile, context: .}
  -!<!python []: {filename: backend/requirements.txt}
